CREATE TABLE PJT_SHOP_MEMBER(
    ID VARCHAR2(20 BYTE) NOT NULL PRIMARY KEY, 
	PASSWORD CHAR(64 BYTE) NOT NULL , 
	SESSION_LEVEL NUMBER(1,0) NOT NULL , 
	NAME VARCHAR2(10 BYTE) NOT NULL , 
	NICK VARCHAR2(20 BYTE) NOT NULL , 
	EMAIL VARCHAR2(100 BYTE) NOT NULL , 
	CONTACT VARCHAR2(13 BYTE), 
	ADDR1 VARCHAR2(100 BYTE), 
	ADDR2 VARCHAR2(100 BYTE), 
	ADDR3 VARCHAR2(100 BYTE), 
	REG_DATE DATE DEFAULT SYSDATE, 
	LOGIN_DATE DATE, 
	UP_DATE DATE, 
	EXIT_DATE DATE
);


CREATE TABLE PJT_SHOP_FAQ(
    FAQ_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY, 
	QUESTION VARCHAR2(200 BYTE) NOT NULL , 
	ANSWER VARCHAR2(4000 BYTE) NOT NULL , 
	REG_DATE DATE DEFAULT sysdate
);


CREATE TABLE PJT_SHOP_QNA(
    QNA_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY, 
	REG_ID VARCHAR2(20 BYTE) NOT NULL REFERENCES PJT_SHOP_MEMBER(ID), 
	REG_DATE DATE DEFAULT sysdate, 
	TITLE VARCHAR2(80 BYTE) NOT NULL , 
	CONTENT VARCHAR2(4000 BYTE) NOT NULL , 
	UPDATE_DATE DATE, 
	REPLY VARCHAR2(4000 BYTE), 
	REPLY_DATE DATE
);


CREATE TABLE PJT_SHOP_FREE(	
    FREE_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY, 
	REG_ID VARCHAR2(20 BYTE) NOT NULL REFERENCES PJT_SHOP_MEMVER(ID), 
	REG_DATE DATE DEFAULT sysdate, 
	CONTENT VARCHAR2(4000 BYTE), 
	REPLY VARCHAR2(4000 BYTE), 
	DEPTH NUMBER(1,0) DEFAULT 0, 
	STEP NUMBER DEFAULT 0
);


CREATE TABLE PJT_SHOP_PRODUCT (
    PRODUCT_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY, 
	PRICE NUMBER(10,0) NOT NULL , 
	NAME VARCHAR2(80 BYTE) NOT NULL , 
	ORIGIN_COUNTRY VARCHAR2(20 BYTE) NOT NULL , 
	SELL_COUNTRY VARCHAR2(20 BYTE) NOT NULL , 
	REG_DATE DATE DEFAULT sysdate, 
	ONE_SENTENCE VARCHAR2(200 BYTE), 
	DESCRIPTION VARCHAR2(4000 BYTE), 
	IMAGES VARCHAR2(80 BYTE), 
	STOCK NUMBER(5,0)
);


CREATE TABLE PJT_SHOP_PURCHASE(
    PURCHASE_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY, 
	BUYER_ID VARCHAR2(20 BYTE) REFERENCES PJT_SHOP_MEMBER(ID), 
	RECEIVER_NAME VARCHAR2(10 BYTE) NOT NULL , 
	RECEIVER_CONTACT VARCHAR2(13 BYTE) NOT NULL , 
	RECEIVER_ADDR1 VARCHAR2(100 BYTE) NOT NULL , 
	RECEIVER_ADDR2 VARCHAR2(100 BYTE) NOT NULL , 
	RECEIVER_ADDR3 VARCHAR2(100 BYTE) NOT NULL , 
	DELIVERY_MEMO VARCHAR2(200 BYTE), 
	PAY_METHOD CHAR(4 BYTE) NOT NULL , 
	TRANSFER_NAME VARCHAR2(10 BYTE), 
	CASH_RECEIPT VARCHAR2(20 BYTE), 
	CARD_NUMBER CHAR(19 BYTE), 
	CARD_CVC CHAR(3 BYTE)
);


CREATE TABLE PJT_SHOP_PURCHASE_DETAIL(
    PURCHASE_NO CHAR(5 BYTE) NOT NULL REFERENCES PJT_SHOP_PURCHASE(PURCHASE_NO), 
	PRODUCT_NO CHAR(5 BYTE) NOT NULL REFERENCES PJT_SHOP_PRODUCT(PRODUCT_NO), 
	COUNT NUMBER(5,0) DEFAULT 1,
    CONSTRAINT PJT_SHOP_PURCHASE_DETAIL_PK PRIMARY KEY(PURCHASE_NO,PRODUCT_NO)
);


CREATE TABLE PJT_SHOP_BASKET(
    ID VARCHAR2(20 BYTE) NOT NULL REFERENCES PJT_SHOP_MEMBER(ID), 
	PRODUCT_NO CHAR(5 BYTE) NOT NULL REFERENCES PJT_SHOP_PRODUCT(PRODUCT_NO), 
	COUNT NUMBER(5,0) DEFAULT 1, 
    CONSTRAINT PJT_SHOP_BASKET_PK PRIMARY KEY(ID,PRODUCT_NO)
    );