
  CREATE TABLE "TRACK11"."PJT_SHOP_BASKET" 
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRODUCT_NO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"COUNT" NUMBER(5,0) DEFAULT 1, 
	 CONSTRAINT "PJT_SHOP_BASKET_PK" PRIMARY KEY ("ID", "PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("ID")
	  REFERENCES "TRACK11"."PJT_SHOP_MEMBER" ("ID") ENABLE, 
	 FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES "TRACK11"."PJT_SHOP_PRODUCT" ("PRODUCT_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_FAQ" 
   (	"FAQ_NO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"QUESTION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ANSWER" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate, 
	"REG_ID" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("FAQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("REG_ID")
	  REFERENCES "TRACK11"."PJT_SHOP_MEMBER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_MEMBER" 
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" CHAR(64 BYTE) NOT NULL ENABLE, 
	"SESSION_LEVEL" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"NAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NICK" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(13 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"ADDR3" VARCHAR2(100 BYTE), 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"LOGIN_DATE" DATE, 
	"UP_DATE" DATE, 
	"EXIT_DATE" DATE, 
	"OTHERS" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_PRODUCT" 
   (	"PRODUCT_NO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"ORIGIN_COUNTRY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SELL_COUNTRY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate, 
	"ONE_SENTENCE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"IMAGES" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER(5,0), 
	"SELL_COUNT" NUMBER(5,0) DEFAULT 0, 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"SHOP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("SHOP")
	  REFERENCES "TRACK11"."PJT_SHOP_SHOP" ("SHOP") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_PURCHASE" 
   (	"PURCHASE_NO" CHAR(11 BYTE) NOT NULL ENABLE, 
	"BUYER_ID" VARCHAR2(20 BYTE), 
	"RECEIVER_NAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"RECEIVER_CONTACT" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"RECEIVER_ADDR1" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RECEIVER_ADDR2" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RECEIVER_ADDR3" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DELIVERY_MEMO" VARCHAR2(200 BYTE), 
	"PAY_METHOD" CHAR(4 BYTE) NOT NULL ENABLE, 
	"TRANSFER_NAME" VARCHAR2(10 BYTE), 
	"CASH_RECEIPT" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"REASON" VARCHAR2(200 BYTE), 
	"MERCHANT_UID" VARCHAR2(30 BYTE), 
	 PRIMARY KEY ("PURCHASE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("BUYER_ID")
	  REFERENCES "TRACK11"."PJT_SHOP_MEMBER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_PURCHASE_DETAIL" 
   (	"PURCHASE_NO" CHAR(11 BYTE) NOT NULL ENABLE, 
	"PRODUCT_NO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"COUNT" NUMBER(5,0) DEFAULT 1, 
	 CONSTRAINT "PJT_SHOP_PURCHASE_DETAIL_PK" PRIMARY KEY ("PURCHASE_NO", "PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("PURCHASE_NO")
	  REFERENCES "TRACK11"."PJT_SHOP_PURCHASE" ("PURCHASE_NO") ENABLE, 
	 FOREIGN KEY ("PRODUCT_NO")
	  REFERENCES "TRACK11"."PJT_SHOP_PRODUCT" ("PRODUCT_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_QNA" 
   (	"QNA_NO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"REG_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate, 
	"TITLE" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"UPDATE_DATE" DATE, 
	"REPLY" VARCHAR2(4000 BYTE), 
	"REPLY_DATE" DATE, 
	 PRIMARY KEY ("QNA_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("REG_ID")
	  REFERENCES "TRACK11"."PJT_SHOP_MEMBER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "TRACK11"."PJT_SHOP_SHOP" 
   (	"SHOP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("SHOP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

